### PR TITLE
Remove Dropbox backend

### PR DESCRIPTION
**Pull request by gabrielcowley**
_This PR has a staging branch, which means a production build of this branch exists and can be launched. [**Click here**](https://www.landmarker.io/staging/remove_dropbox) to preview this PR._

The Dropbox backend is removed in this PR. Dropbox API v2 is going to be deprecated soon and so we're removing the backend altogether.

### CODE REVIEW

**Comment by patricksnape** [comment]
Looks good to me

**Comment by jabooth** [comment]
Unfortunately this is broken for users that are already signed into `Dropbox` when they visit the new version.

To reproduce:

1. Go to landmarker.io and sign in to Dropbox
2. On the same browser, visit `landmarker.io/staging/remove_dropbox`

What should happen: I should be taken to the main menu
What does happen: I get nothing loaded (and no error in the console)

**Comment by gabrielcowley** [comment]
@jabooth Okay, I'll add a fix for this.

**Comment by gabrielcowley** [comment]
@jabooth The main menu now opens if Landmarker Server is not the backend type in the application cache.

**Comment by jabooth** [comment]
Looks great! LGTM.

**Pull request merged**
